### PR TITLE
style: Create `.pre-commit-config.yaml`

### LINKED ISSUE #124: [FEATURE] Add `.pre-commit-config.yml`
I noticed that most of (if not all) the steps of the Contributing wiki can be automated via [**pre-commit**](https://pre-commit.com/). Having [**pre-commit**](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions.

I'd be more than happy to take this up.

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Fixes #124

### CODE REVIEW

**Comment by freud14** [comment]
Hi @SauravMaheshkar, thanks for the PR. For the PyLint hook, the directories should be be `poutyne/ tests/` and not `src/`. For the Black hook, it could be nice to put the required version in the hook. Currently, in the `styling_requirements.txt` file, I have the following:

    black~=22.3
    black[jupyter]

Thank you.

Frédérik

**Comment by SauravMaheshkar** [comment]
I have updated the directories in the pylint hook to have `poutyne/` and `tests/` however for the black hook we use the official hook which doesn't include the `jupyter` extension.

**Comment by freud14** [comment]
Hi, I just tested the hook but the Black one does not seem to work properly. I get a version error (`Oh no! 💥 💔 💥 The required version 22 does not match the running version 0.1.dev1+gae2c075!`). In another project, we use this instead:
    
    -   repo: local
        hooks:
        - id: black
          name: black
          entry: black
          language: python
          types_or: [python, pyi]
          additional_dependencies: [black~=22.3, "black[jupyter]"]

**Comment by SauravMaheshkar** [comment]
Ah yes of-course that makes sense. Switched to a local black hook in [795ccf7](https://github.com/GRAAL-Research/poutyne/pull/160/commits/795ccf79844a8005b853ee546405a01a13efde37)

**Comment by SauravMaheshkar** [comment]
@freud14 Request for Review

**Pull request merged**
