### PR TITLE
Coloring the progress output for highlighting it

### PR DESCRIPTION
**Pull request by davebulaval**
(Ref #64)
Allow the user to trigger a default coloring scheme for the progress of the training.
Allow the user to specify a coloring scheme for the progress of the training.

### Example with the default coloring settings:

During training:
image

At the end of the training: (test is not colored)
image (1)

### CODE REVIEW

**Comment by freud14** [comment]
We might want to be able to pass a subset of the keys so that the user can change some colors but not others.

**Comment by freud14** [comment]
Also, it might be a good idea to add colorama in the [extra-requirements](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) and in the tests requirements.

**Comment by davebulaval** [comment]
> We might want to be able to pass a subset of the keys so that the user can change some colors but not others.

I've thought about it and I don't have an opinion. If we do so, I will remove the validation of the user colors.
Do we print a warnings saying that we took some default colors ?

**Comment by davebulaval** [comment]
> Also, it might be a good idea to add colorama in the [extra-requirements](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) and in the tests requirements.

I've also thought about it and was not sure if we wanted to have it in the dependencies. Is up to you.

**Comment by davebulaval** [comment]
Will add to extra_requirements with message.
Will add in tests and keep skipif.
Will remove validate all args and override with user instead.

**Pull request merged**
